name = "auxlo-neo"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Cron triggers
[triggers]
crons = ["*/5 * * * *", "0 * * * *"]

[[kv_namespaces]]
binding = "SESSIONS"
id = "f23e9f4c84fb480d846953cb64a5b57c"

[[kv_namespaces]]
binding = "MEMORY"
id = "ed1a3572eaa04ab08ae601f08e5d6801"

[[kv_namespaces]]
binding = "CONFIG"
id = "60a8e92dca8c4dd28a5246a165c4280a"

[[d1_databases]]
binding = "DB"
database_name = "auxlo-docs"
database_id = "def3fb93-73c1-460d-b855-1e1cad6e42b0"

[vars]
EXECUTOR_URL = "https://auxlo-muscle.vercel.app/exec"
