name = "auxlo-neo"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "SESSIONS"
id = "f23e9f4c84fb480d846953cb64a5b57c"

[[kv_namespaces]]
binding = "MEMORY"
id = "ed1a3572eaa04ab08ae601f08e5d6801"

[[kv_namespaces]]
binding = "CONFIG"
id = "60a8e92dca8c4dd28a5246a165c4280a"

[vars]
EXECUTOR_URL = "https://auxlo-muscle.vercel.app/exec"
